name: TV_video apk builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
         android-home: $ANDROID_HOME
         android-version: '30'
         build-tools-version: '30.0.3'
         sdk-tools-version: '2021.1.1'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK as astifact
        uses: actions/upload-artifact@v3
        with:
         name: app-debug.apk
         path: app/build/output/apk/debug/app-debug.apk
         
